main/urls.py
from django.urls import path
from .views import *

app_name = 'Main'

urlpatterns = [
    path('', home_page, name='HomePage'),
    path('login/', login_page, name='Login'),
    path('register/', register_page, name='Register'),
    path('dashboard/edit-<slug:article_id>/', dashboard_page, name='Dashboard'),
    path('logout/', logout_page, name='Logout'),
    path('article/<uuid:article_id>/', view_page, name='Article'),
    path('del/<uuid:article_id>/', delete_article, name='Delete')
]

miniBlog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('main.urls')),
    path('admin/', admin.site.urls),
]

main/models.py
from django.db import models
from django.contrib.auth.models import User
import uuid

class article(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    article_id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, unique=True, blank=False)
    title = models.CharField(unique=True, max_length=700, blank=False, editable=True)
    subtitle = models.TextField(unique=True, blank=True, editable=True)
    summary_intro = models.TextField(verbose_name="Introduction", max_length=500, unique=True, null=False, blank=False, editable=True, default='')
    body = models.TextField(unique=True, blank=False, null=False, editable=True)
    date_published = models.DateTimeField(auto_now_add=True)
    date_modified = models.DateTimeField(auto_now=True)

    def __repr__(self):
        return f"Title: {self.title} By: {self.owner}"

main/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from .models import *

def home_page(request, *args, **kwargs):
    articles = article.objects.order_by('-date_published')
    return render(request, 'index.html', {'articles': articles})

def login_page(request, *args, **kwargs):
    if request.method == "POST":
        try:
            logged_user = authenticate(request, username=request.POST['username'], password=request.POST['password'])
            login(request, logged_user) if logged_user is not None else print('Error Logging in, logged user produced:', logged_user)
        except Exception:
            return 
        return redirect('Main:HomePage')
    return render(request, 'login.html')

def register_page(request, *args, **kwargs):
    if request.method == 'POST':
        try:
            User.objects.create_user(
                username=request.POST['username'],
                first_name=request.POST['first_name'],
                last_name=request.POST['last_name'],
                email=request.POST['e_mail'],
                password=request.POST['password'],
            )
            logged_user = authenticate(request, username=request.POST['username'], password=request.POST['password'])
            login(request, logged_user) if logged_user is not None else print('Error Logging in, logged user produced:', logged_user)
            return redirect('Main:Dashboard')
        except Exception:
            print('Error Occured')
            return redirect('Main:Homepage')
    return render(request, 'register.html')

@login_required(login_url='Main:Login')
def dashboard_page(request, article_id, *args, **kwargs):
    if request.method == 'POST':
        if article_id != 'new-article':
            try:
                article.objects.filter(article_id=article_id).update(
                    title=request.POST['title'],
                    subtitle=request.POST['subtitle'],
                    summary_intro= request.POST['introduction'],
                    body=request.POST['body']
                )
                print('Article Updated Successfuly')
                return redirect('Main:HomePage')
            except Exception:
                print(Exception)
        else:
            try:
                article.objects.create(
                    owner=request.user,
                    title=request.POST['title'],
                    subtitle=request.POST['subtitle'],
                    summary_intro= request.POST['introduction'],
                    body=request.POST['body']
                )
                print('Article Created Successfuly')
                return redirect('Main:HomePage')
            except Exception:
                print(Exception)
    return render(request, 'dashboard.html', {
        'article': article_id if article_id == 'new-article' else article.objects.get(article_id=article_id)
    })

@login_required(login_url='Main:Login')
def logout_page(request, *args, **kwargs):
    logout(request)
    print(request.user)
    return redirect('Main:HomePage')

def view_page(request, article_id, *args, **kwargs):
    individual_article = article.objects.get(article_id=article_id)
    return render(request, 'view.html', {'article_detail': individual_article})

@login_required(login_url='Main:Login')
def delete_article(request, article_id, *args, **kwargs):
    try:
        article_to_delete = article.objects.get(article_id=article_id)
        article_to_delete.delete()
        return redirect('Main:HomePage')
    except Exception:
        return redirect('Main:HomePage')

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{%static 'base_style.css' %}">
    {% block style %}{% endblock %}
    <title>MiniBlog{% block title %}{% endblock %}</title>
</head>
<body>
    {% block body %}
    {% endblock %}
</body>
</html>

templates/dashboard.html
{% extends 'base.html' %} 

{% load static %} 

{% block style %}
    <link rel="stylesheet" href="{% static 'dash_style.css' %}" />
{% endblock %}
{% block title %} | Dashboard{% endblock %} 

{% block body %}
    <nav class="nav-bar">
        <a href="{% url 'Main:HomePage' %}" class="nav-item">Home</a>
        <a href="{% url 'Main:Logout' %}" class="nav-item">Logout</a>
    </nav>
    <section>
        <form action="" method="post">
            {% csrf_token %}
            <div class="create-new-article">
                <div class="main-title">Create/Update Post</div>
                {% if article != 'new-article' %}
                    <div class="set-main">
                            <div class="set-info">
                                <label>Title:</label> <input required type="text" name="title" value="{{article.title}}" />
                            </div>
                            <div class="set-info">
                                <label>Subtitle:</label> <input required type="text" name="subtitle" value="{{article.subtitle}}" />
                            </div>
                            <div class="set-info">
                                <label>Introduction:</label> 
                                <textarea required name="introduction" placeholder="Maximum length: 500" maxlength="500">{{article.summary_intro}}</textarea>
                            </div>
                            <div class="set-info" id="textarea-part">
                                <label>Body:</label> 
                                <textarea rows="6" required name="body">{{article.body}}</textarea>
                            </div>
                    </div>
                    <button class="Submit-btn">Update</button>
                {% else%}
                <div class="set-main">
                    <div class="set-info">
                        <label>Title:</label> <input required type="text" name="title" />
                    </div>
                    <div class="set-info">
                        <label>Subtitle:</label> <input required type="text" name="subtitle" />
                    </div>
                    <div class="set-info">
                        <label>Introduction:</label> <textarea required name="introduction" placeholder="Maximum length: 500" maxlength="500"></textarea>
                    </div>
                    <div class="set-info" id="textarea-part">
                        <label>Body:</label> <textarea rows="6" required name="body"></textarea>
                    </div>
                </div>
                <button class="Submit-btn">Create</button>
                {% endif%}
            </div>
        </form>
    </section>

{% endblock %}

templates/index.html
{% extends 'base.html' %}

{% load static %}

{% block style %}
    <link rel="stylesheet" href="{% static 'home_style.css' %}" />
{% endblock %}

{% block title %} | Home{% endblock %}

{% block body %}
    <nav class='nav-bar'>
        {% if request.user.is_authenticated %}
            <a href="{% url 'Main:Dashboard' 'new-article' %}" class="nav-item">Dashboard</a>
            <a href="{% url 'Main:Logout' %}" class="nav-item">Logout</a>
        {% else %}
            <a href="{% url 'Main:Register' %}" class="nav-item">Sign Up</a>
            <a href="{% url 'Main:Login' %}" class="nav-item">Login</a>
        {% endif %}
    </nav>
    <section class="Article-view">
        {% for article in articles %}
        <div class="article">
            <div class="title">{{article.title}}</div>
            <div class="subtitle">{{article.subtitle}} <span class="date">{{article.date_published}}</span></div>
            <div class="body">{{article.summary_intro}}<span style="color: rgba(0, 0, 0, 0.562);">.....</span></div>
            <div class="anchors">
                <a href="{% url 'Main:Article' article.article_id %}" class="anchor-link">View Article</a>
                {% if article.owner == request.user %}
                    <a href="{% url 'Main:Dashboard' article.article_id %}" class="anchor-link">Edit Post</a>
                    <a href="{% url 'Main:Delete' article.article_id %}" class="anchor-link">Delete Post</a>
                {% endif %}
            </div>
        </div>
        {% endfor %}
    </section>
{% endblock %}

templates/login.html
{% extends 'base.html' %}

{% load static %}

{% block style %}
    <link rel="stylesheet" href="{% static 'auth_style.css' %}">
{% endblock %}

{% block title %} | Login{% endblock %}
{% block body %}
    <section class="input-form-sect">
        <div class="input-form-arr">
            <div class='title'>Login</div>
            <form class="input-form" action="" method="post">
                {% csrf_token %}
                <input type="text" required placeholder="Username" name="username" class="input" id="username">
                <input type="password" required placeholder="Password" name="password" class="input" id="password">
                <button type="submit" class="subBtn" id="subBtn">Login</button>
            </form>
            <div class="alt-prompt">
                Not Yet Registered? <a href="{% url 'Main:Register' %}">Sign Up Here</a>
            </div>
        </div>
    </section>
{% endblock %}

templates/register.html
{% extends 'base.html' %}

{% load static %}

{% block style %}
    <link rel="stylesheet" href="{% static 'auth_style.css' %}">
{% endblock %}

{% block title %} | Register{% endblock %}
{% block body %}
    <section class="input-form-sect">
        <div class="input-form-arr">
            <div class="title">Sign Up</div> 
            <form class="input-form" action="" method="post">
                {% csrf_token %}
                <input type="text" name="username" class="input" required placeholder="Username" id="username">
                <input type="text" name="first_name" class="input" required placeholder="First Name" id="first-name">
                <input type="text" name="last_name" class="input" required placeholder="Last Name" id="last-name">
                <input type="email" name="e_mail" class="input" required placeholder="E-Mail" id="email">
                <input type="password" name="password" class="input" required placeholder="Password" id="password">
                <button type="submit" class="subBtn" id="subBtn">Sign Up</button>
            </form>
            <div class="alt-prompt">
                Already Registered? <a href="{% url 'Main:Login' %}">Login Here</a>
            </div>
        </div>
    </section>
{% endblock %}

templates/view.html
{% extends 'base.html' %}

{% load static %}

{% block style %}
    <link rel="stylesheet" href="{% static 'home_style.css' %}" />
{% endblock %}

{% block body %}
    <nav class='nav-bar'>
        {% if request.user.is_authenticated %}
            <a href="{% url 'Main:HomePage' %}" class="nav-item">Home</a>
            <a href="{% url 'Main:Dashboard' 'new-article' %}" class="nav-item">Dashboard</a>
            <a href="{% url 'Main:Logout' %}" class="nav-item">Logout</a>
        {% else %}
            <a href="{% url 'Main:HomePage' %}" class="nav-item">Home</a>
            <a href="{% url 'Main:Register' %}" class="nav-item">Sign Up</a>
            <a href="{% url 'Main:Login' %}" class="nav-item">Login</a>
        {% endif %}
    </nav>
    <section class="Article-detail">
        <div>
            <div class="article-title">
                {{article_detail.title}}
            </div>
            <div class="article-subtitle">
                {{article_detail.subtitle}}
                <span class="article-date-pub">
                    {{article_detail.date_published}}
                </span>
                {% if request.user == article_detail.owner %}
                <div class="article-date-pub">
                    Date modified by you: {{article_detail.date_modified}}
                </div>
                {% endif %}
            </div>
            <div class="article-body">
                {{article_detail.body}}
            </div>
            <div class="article-author">
                {% if article_detail.owner == request.user %}
                    Author: You
                    <div class="article-modify">
                        <a href="{% url 'Main:Dashboard' article_detail.article_id %}" class="anchor-link">Edit Post</a>
                        <a href="{% url 'Main:Delete' article_detail.article_id %}" class="anchor-link">Delete Post</a>
                    </div>
                {% else %}
                    By {{ article_detail.owner.first_name }} {{ article_detail.owner.last_name }} 
                    <div class="article-owner-username anchor-link" title="{{ article_detail.owner.first_name }} {{ article_detail.owner.last_name }}'s Username">
                        @{{article_detail.owner.username}}
                    </div>
                {% endif %}
            </div>
        </div>
    </section>
{% endblock %}